version: '2.1'
services:
 postgres:
    image: postgres:15.0-alpine
    volumes:
      - my_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./core/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 3s
      timeout: 3s
      retries: 3

 mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  my_postgres_data:
  mongo_data: