name: Python application

on:
  push:
    branches: [ "feature/ci_cd" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide

    - name: mypy action
      uses: sasanquaneuf/mypy-github-action@releases/v1.3
